name: Call shared workflow

on:
  push:

env:
  MY_VAR1: "me and me"
  MY_VAR2: v1.0.2 # you should lock to version tag


jobs:
  build:
    uses: vegarringdal/action2/.github/workflows/action2.yaml@main
    with: 
      config: "static value"
    secrets:
      TEST1: ${{ secrets.TEST1 }}